export const strings = {
  figma: "figma",
  github: "github",
  deploy: "ver online",
  myRole: "minha função",
  developmentTime: "tempo estimado",
  projectType: "tipo de projeto",
  general: "visão geral",
  motivation: "motivação",
  highlights: "destaques",
  technologies: "principais tecnologias",
  wasNotIncludedMinorLibraries: "não estão inclusas bibliotecas menores",
  developmentProcess: "processo de desenvolvimento",
  images: "imagens",
  didYouLikeThisProject: "gostou do projeto ?",
  letsTalk: {
    firstPart: "vamos",
    talk: "conversar!",
    lastPart: "eu te mostro mais detalhes sobre este projeto e outros!",
  },
  phaseName: ["primeira fase", "segunda fase", "terceira fase", "quarta fase"],
};
